version: '3.9'

services:
  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: mongo-vms
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-vms-app
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:mongoo@mongo:27017/vms
      - MONGODB_AUTH_DB=vms-auth
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
